using System.Reflection;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace GoldFieldsHR.Infrastructure.Common;

/// <summary>Shared company letterhead assets for every QuestPDF report generated by this app.</summary>
internal static class PdfBranding
{
    private static readonly Lazy<byte[]?> CachedLogo = new(LoadEmbeddedLogo);

    public const string CompanyName = "Rams Mining Technologies";

    /// <summary>The Rams Mining logo, or null if the embedded resource is missing — callers should render without it rather than throw.</summary>
    public static byte[]? Logo => CachedLogo.Value;

    /// <summary>
    /// Renders the standard letterhead — logo, company name, report title/subtitle — into a page header.
    /// Usage: <c>page.Header().Element(header => PdfBranding.RenderLetterhead(header, "Report Title"));</c>
    /// </summary>
    public static void RenderLetterhead(IContainer container, string title, string? subtitle = null)
    {
        container.Row(row =>
        {
            if (Logo is { } logo)
            {
                row.ConstantItem(60).Image(logo);
            }

            row.RelativeItem().PaddingLeft(Logo is null ? 0 : 12).Column(column =>
            {
                column.Item().Text(CompanyName).FontSize(14).Bold();
                column.Item().Text(title).FontSize(12).FontColor(Colors.Grey.Darken1);
                if (subtitle is not null)
                {
                    column.Item().Text(subtitle).FontSize(9).FontColor(Colors.Grey.Medium);
                }
            });
        });
    }

    private static byte[]? LoadEmbeddedLogo()
    {
        var assembly = Assembly.GetExecutingAssembly();
        using var stream = assembly.GetManifestResourceStream("GoldFieldsHR.Infrastructure.Resources.rams-logo.png");
        if (stream is null)
        {
            return null;
        }

        using var memory = new MemoryStream();
        stream.CopyTo(memory);
        return memory.ToArray();
    }
}
